test:
  adapter: sqlite3
  database: test.db

<% database_url = URI.parse(ENV['DATABASE_URL'] || '') %>
<%= ENV['RACK_ENV'] %>:
  adapter: em_postgresql
  username: <%= database_url.user %>
  password: <%= database_url.password %>
  host: <%= database_url.host %>
  database: <%= database_url.path[1..-1] %>
  pool: 6
  connections: 6
